### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [MatsuriDayo/Matsuri#7]
请问是否可以发布到 F-Droid？

**Comment by arm64v8a** [comment]
我没有太多时间，有人来做日常工作， 就可以

发布到 F-Droid 需要符合他们的规范，并为他们提供特殊的编译脚本

https://github.com/SagerNet/SagerNet/tree/dev/bin/fdroid

**Comment by linsui** [comment]
直接使用 SagerNet 的脚本可以吗？F-Droid 要求从源码构建。nekohasekai 为了方便维护单独为 F-Droid 编写了构建脚本，不过直接在编译元数据中执行构建也可以。更新是自动进行的，只要构建过程不变就行。

**Comment by linsui** [comment]
我遇到了一些奇怪的错误。https://gitlab.com/linsui/fdroiddata/-/jobs/2032850601 可以请你看一下吗？和 SagerNet 使用的构建步骤没有什么区别，直接按照 CI 的步骤进行构建的。构建元数据是 https://gitlab.com/linsui/fdroiddata/-/commit/14ac14dd1bf2d80d78379137e9bba74b32304392

**Comment by arm64v8a** [comment]
应该是 keystore 的问题

请在每次编译时把 fdroid keystore 覆盖项目目录下的 release.keystore，并设置 local.properties

```
KEYSTORE_PASS=xxx
ALIAS_NAME=xxx
ALIAS_PASS=xxx
```

**Comment by arm64v8a** [comment]
另外希望修改一下元数据

```yaml
Categories:
  - Internet
License: GPL-3.0-or-later
AuthorName: arm64_v8a
AuthorWebSite: https://matsuridayo.github.io/
SourceCode: https://github.com/MatsuriDayo/Matsuri
IssueTracker: https://github.com/MatsuriDayo/Matsuri/issues
Changelog: https://t.me/Matsuridayo
Donate: https://matsuridayo.github.io/
Bitcoin: 3M3Kq9CcfHeEfSDFhtrMDu9bchHsW1iixK
```

https://matsuridayo.github.io/ 为本项目的文档，目前只有中文，以后会考虑加入英文翻译。
